package kr.co.wizclass.toy.domain.entity.type;

public enum ReportReason {
    SPAM,
    NUDITY_OR_SEXUAL_CONTENT,
    FRAUD_OR_FALSE_INFORMATION,
    HATE_SPEECH_OR_SYMBOLS,
    FALSE_INFORMATION,
    HARASSMENT_OR_BULLYING,
    VIOLENCE_OR_DANGEROUS_ORGANIZATIONS,
    INTELLECTUAL_PROPERTY_VIOLATION
}
